### ISSUE TITLE
hadamard product between sparse and dense tensor in pytorch

### ISSUE THREAD

**Issue by yaokl-nju** [sniklaus/pytorch-extension#2]
hi, are there any implementation of the hadamard product between sparse and dense tensor in pytorch? It's very strange that sparse_a * sparse_b can work, but sparse_a * dense_b can't not work.

**Comment by sniklaus** [comment]
The issue that you opened in the official PyTorch repository is probably more adequate to get an answer to this question: https://github.com/pytorch/pytorch/issues/4456
